version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - my_network

  backend:
    build:
      context: ./visum-backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mysql
    networks:
      - my_network
    restart: on-failure
    command: sh -c "sleep 10 && node server.js"

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: visum
    ports:
      - 3307:3306
    networks:
      - my_network

  frontend:
    build:
      context: ./visum-frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
